# example of adding multiple .cpp files


EXE = programTest

CC = g++

OBJECTS = main.o second.o

LFLAGS = 

CFLAGS = 

$(EXE):				$(OBJECTS)
					$(CC) $(CFLAGS) -o $(EXE) $(OBJECTS) $(LFLAGS)

main.o:				main.cpp
					$(CC) $(CFLAGS) -c main.cpp

second.o:			second.cpp
					$(CC) $(CFLAGS) -c second.cpp

clean:		
					rm -rf $(EXE) $(OBJECTS) *~